#!/bin/sh
# Generated by lis2alpine — prepares the layout for `setup-disk`.
set -eux
disk='/dev/vda'
mnt='/mnt/lis'
apk add --no-progress btrfs-progs e2fsprogs xfsprogs dosfstools parted
for m in ext4; do modprobe "$m" 2>/dev/null || true; done
parted -s '/dev/vda' mklabel msdos
parted -s '/dev/vda' -- mkpart primary 1MiB 1025MiB
parted -s '/dev/vda' set 1 boot on
parted -s '/dev/vda' -- mkpart primary 1025MiB 100%
partprobe '/dev/vda' || true
parted -s '/dev/vdb' mklabel msdos
parted -s '/dev/vdb' -- mkpart primary 1MiB 1025MiB
parted -s '/dev/vdb' set 1 boot on
parted -s '/dev/vdb' -- mkpart primary 1025MiB 100%
partprobe '/dev/vdb' || true
apk add --no-progress mdadm
mdadm --create /dev/md/md0 --run --level=1 --raid-devices=2 '/dev/vda2' '/dev/vdb2'
apk add --no-progress lvm2
pvcreate -ff -y /dev/md/md0
vgcreate vg0 /dev/md/md0
lvcreate -y -L 2G -n swap vg0
mkswap /dev/vg0/swap
lvcreate -y -l 100%FREE -n root vg0
mkfs.ext4 -F /dev/vg0/root
rootdev=/dev/vg0/root
sleep 2
mkfs.ext4 -F '/dev/vda1'
bootdev='/dev/vda1'
mkfs.ext4 -F '/dev/vdb1'
mkdir -p "$mnt"
mount "$rootdev" "$mnt"
umount "$mnt"
mount "$rootdev" "$mnt"
mkdir -p "$mnt/boot"
mount "$bootdev" "$mnt/boot"
BOOTLOADER=grub DISKLABEL=dos KERNELOPTS='console=tty0 console=ttyS0,115200n8 modules=sd-mod,usb-storage,virtio-blk,virtio-pci,ext4,dm-mod,raid1,raid0,raid10,md-mod rootfstype=ext4' BOOTFS=ext4 setup-disk -m sys "$mnt"
for d in dev proc sys; do mount --bind "/$d" "$mnt/$d"; done
chroot "$mnt" apk add --no-progress grub grub-bios
printf 'GRUB_CMDLINE_LINUX_DEFAULT="%s"\nGRUB_TERMINAL="serial console"\nGRUB_SERIAL_COMMAND="serial --unit=0 --speed=115200"\n' 'console=tty0 console=ttyS0,115200n8 modules=sd-mod,usb-storage,virtio-blk,virtio-pci,ext4,dm-mod,raid1,raid0,raid10,md-mod rootfstype=ext4' > "$mnt/etc/default/grub"
echo GRUB_TIMEOUT=5 >> "$mnt/etc/default/grub"
chroot "$mnt" grub-install --target=i386-pc "$disk"
chroot "$mnt" grub-mkconfig -o /boot/grub/grub.cfg
for d in sys proc dev; do umount "$mnt/$d" || true; done
