#!/usr/bin/env python3
"""lis2alpine — translate a LIS document into Alpine Linux answers file & setup script.

Usage: lis2alpine.py FILE.lis.json [--out DIR] [--strict]

Writes answers into DIR (default '.'):
  answers   — Alpine setup-alpine answerfile

Best-effort: core intent that Alpine setup cannot express is reported as a warning;
with --strict any dropped intent exits non-zero (SPEC §2.3).
"""

import argparse
import json
import pathlib
import sys

WARNINGS: list[str] = []


def warn(msg: str) -> None:
    WARNINGS.append(msg)
    print(f"warning: {msg}", file=sys.stderr)


def render_alpine(doc: dict) -> str:
    system = doc.get("system", {}) or {}
    storage = doc.get("storage", {}) or {}
    target = doc.get("target", {}) or {}
    software = doc.get("software", {}) or {}
    scripts = doc.get("scripts", {}) or {}
    users = doc.get("users", []) or []

    lines: list[str] = ["# Generated by lis2alpine (Linux Installation Specification)", ""]

    keymap = (system.get("keymap", {}) or {}).get("console", "us")
    lines.append(f"KEYMAPOPTS=\"{keymap} {keymap}\"")
    lines.append(f"HOSTNAMEOPTS=\"{system.get('hostname', 'lis-test-host')}\"")
    lines.append("INTERFACESOPTS=\"auto eth0\niface eth0 inet dhcp\n\"")
    lines.append("DNSOPTS=\"-n 8.8.8.8\"")
    lines.append(f"TIMEZONEOPTS=\"{system.get('timezone', 'UTC')}\"")
    lines.append("PROXYOPTS=\"none\"")
    lines.append("APKREPOSOPTS=\"-c\"")
    lines.append("SSHDOPTS=\"openssh\"")
    lines.append("NTPOPTS=\"chrony\"")

    disks = [(d.get("match", {}) or {}).get("path") for d in target.get("disks", []) if (d.get("match", {}) or {}).get("path")]
    disk_target = disks[0] if disks else "/dev/vda"
    lines.append(f"DISKOPTS=\"-m sys {disk_target}\"")
    lines.append("LBUOPTS=\"none\"")
    lines.append("APKCACHEOPTS=\"none\"")

    for u in users:
        if u.get("name") != "root":
            lines.append(f"USEROPTS=\"-a -g wheel {u['name']}\"")
            if h := (u.get("password") or {}).get("hash"):
                lines.append(f"USERPASSWORD=\"{h}\"")
            break

    if doc.get("keys"):
        warn("hardware key matrix (keys[]) requires cryptsetup/fido2 post-install setup on Alpine")

    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Translate LIS document to Alpine answerfile and optionally apply directly.")
    ap.add_argument("file", type=pathlib.Path)
    ap.add_argument("--out", type=pathlib.Path, default=pathlib.Path("."))
    ap.add_argument("--strict", action="store_true", help="exit non-zero if core intent dropped")
    ap.add_argument("--apply", "-a", action="store_true", help="directly execute setup-alpine with answers on live system")
    args = ap.parse_args()

    doc = json.loads(args.file.read_text())
    if not str(doc.get("lis", "")).startswith("0.1."):
        sys.exit(f"unsupported LIS version: {doc.get('lis')!r}")

    ans = render_alpine(doc)
    args.out.mkdir(parents=True, exist_ok=True)
    ans_file = args.out / "answers"
    ans_file.write_text(ans)
    print(f"wrote {ans_file} ({len(WARNINGS)} warning(s))")

    if args.apply:
        import shutil
        import subprocess
        if not shutil.which("setup-alpine"):
            sys.exit("error: --apply requested, but 'setup-alpine' binary is not found on PATH (are you running on Alpine LiveCD?)")
        cmd = ["setup-alpine", "-f", str(ans_file)]
        print(f"executing Alpine installer: {' '.join(cmd)}")
        res = subprocess.run(cmd)
        return res.returncode

    if args.strict and WARNINGS:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
