#!/usr/bin/env python3
"""lis2debian — translate a LIS document into Debian preseed file (preseed.cfg).

Usage: lis2debian.py FILE.lis.json [--out DIR] [--strict]

Writes preseed.cfg into DIR (default '.'):
  preseed.cfg — Debian installer (d-i) preseed configuration

Best-effort: core intent that d-i preseed cannot express is reported as a warning;
with --strict any dropped intent exits non-zero (SPEC §2.3).
"""

import argparse
import json
import pathlib
import sys

WARNINGS: list[str] = []


def warn(msg: str) -> None:
    WARNINGS.append(msg)
    print(f"warning: {msg}", file=sys.stderr)


def render_preseed(doc: dict) -> str:
    system = doc.get("system", {}) or {}
    boot = doc.get("boot", {}) or {}
    software = doc.get("software", {}) or {}
    scripts = doc.get("scripts", {}) or {}
    users = doc.get("users", []) or []

    lines: list[str] = ["# Generated by lis2debian (Linux Installation Specification)", ""]

    # Locale, Keyboard, Timezone
    lines.append(f"d-i debian-installer/locale string {system.get('locale', 'en_US.UTF-8')}")
    lines.append(f"d-i keyboard-configuration/xkb-keymap select {(system.get('keymap', {}) or {}).get('console', 'us')}")
    lines.append(f"d-i clock-setup/utc boolean {str(system.get('hwclock') == 'utc' or True).lower()}")
    lines.append(f"d-i time/zone string {system.get('timezone', 'UTC')}")

    if host := system.get("hostname"):
        lines.append(f"d-i netcfg/get_hostname string {host}")

    # Users
    for u in users:
        if u["name"] == "root":
            if h := (u.get("password") or {}).get("hash"):
                lines.append(f"d-i passwd/root-password-crypted password {h}")
        else:
            lines.append(f"d-i passwd/user-fullname string {u.get('comment') or u['name']}")
            lines.append(f"d-i passwd/username string {u['name']}")
            if h := (u.get("password") or {}).get("hash"):
                lines.append(f"d-i passwd/user-password-crypted password {h}")

    # Packages & apps
    pkgs = list(software.get("packages", []))
    for app in software.get("apps", []):
        if isinstance(app, str):
            pkgs.append(app)
        elif isinstance(app, dict):
            if name := (app.get("package") or app.get("name")):
                pkgs.append(name)
    if pkgs:
        lines.append(f"d-i pkgsel/include string {' '.join(pkgs)}")

    # Early / Late commands
    early = []
    for stage in ("pre_install", "pre", "post_storage"):
        for s in scripts.get(stage, []):
            if c := s.get("content"):
                early.append(c)
    if early:
        lines.append(f"d-i preseed/early_command string {'; '.join(early)}")

    late = []
    for stage in ("post_install", "post", "pre_reboot", "on_success"):
        for s in scripts.get(stage, []):
            if c := s.get("content"):
                late.append(f"in-target sh -c {json.dumps(c)}")

    for u in users:
        if u_scripts := u.get("scripts", {}):
            for stage in ("post_install", "firstboot"):
                for s in u_scripts.get(stage, []):
                    if c := s.get("content"):
                        late.append(f"in-target su - {u['name']} -c {json.dumps(c)}")

    if late:
        lines.append(f"d-i preseed/late_command string {'; '.join(late)}")

    if doc.get("keys"):
        warn("hardware key matrix (keys[]) not translated into preseed.cfg; requires in-target cryptenroll")

    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Translate LIS document to Debian preseed and optionally apply directly.")
    ap.add_argument("file", type=pathlib.Path)
    ap.add_argument("--out", type=pathlib.Path, default=pathlib.Path("."))
    ap.add_argument("--strict", action="store_true", help="exit non-zero if core intent dropped")
    ap.add_argument("--apply", "-a", action="store_true", help="directly pass preseed.cfg to debconf-set-selections on live system")
    args = ap.parse_args()

    doc = json.loads(args.file.read_text())
    if not str(doc.get("lis", "")).startswith("0.1."):
        sys.exit(f"unsupported LIS version: {doc.get('lis')!r}")

    cfg = render_preseed(doc)
    args.out.mkdir(parents=True, exist_ok=True)
    cfg_file = args.out / "preseed.cfg"
    cfg_file.write_text(cfg)
    print(f"wrote {cfg_file} ({len(WARNINGS)} warning(s))")

    if args.apply:
        import shutil
        import subprocess
        if not shutil.which("debconf-set-selections"):
            sys.exit("error: --apply requested, but 'debconf-set-selections' binary is not found on PATH (are you running on Debian Installer?)")
        print(f"applying preseed choices to debconf: {cfg_file}")
        with open(cfg_file, "r") as f:
            res = subprocess.run(["debconf-set-selections"], stdin=f)
            return res.returncode

    if args.strict and WARNINGS:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
