#!/usr/bin/env python3
"""lis2alpine — translate a LIS document into Alpine Linux answers file & setup script.

Usage: lis2alpine.py FILE.lis.json [--out DIR] [--strict]

Writes answers into DIR (default '.'):
  answers   — Alpine setup-alpine answerfile

Best-effort: core intent that Alpine setup cannot express is reported as a warning;
with --strict any dropped intent exits non-zero (SPEC §2.3).
"""

import argparse
import json
import pathlib
import sys

WARNINGS: list[str] = []


def warn(msg: str) -> None:
    WARNINGS.append(msg)
    print(f"warning: {msg}", file=sys.stderr)


def render_alpine(doc: dict) -> str:
    system = doc.get("system", {}) or {}
    storage = doc.get("storage", {}) or {}
    target = doc.get("target", {}) or {}
    software = doc.get("software", {}) or {}
    scripts = doc.get("scripts", {}) or {}
    users = doc.get("users", []) or []

    lines: list[str] = ["# Generated by lis2alpine (Linux Installation Specification)", ""]

    keymap = (system.get("keymap", {}) or {}).get("console", "us")
    lines.append(f"KEYMAPOPTS=\"{keymap} {keymap}\"")
    lines.append(f"HOSTNAMEOPTS=\"-n {system.get('hostname', 'alpine')}\"")
    lines.append("INTERFACESOPTS=\"auto eth0\niface eth0 inet dhcp\n\"")

    lines.append(f"TIMEZONEOPTS=\"-z {system.get('timezone', 'UTC')}\"")
    lines.append("PROXYOPTS=\"none\"")
    lines.append("APKREPOSOPTS=\"-c\"")

    for u in users:
        if u["name"] != "root":
            lines.append(f"USEROPTS=\"-a -g wheel {u['name']}\"")
            if h := (u.get("password") or {}).get("hash"):
                lines.append(f"USERPASSWORD=\"{h}\"")
            break

    disks = [(d.get("match", {}) or {}).get("path") for d in target.get("disks", []) if (d.get("match", {}) or {}).get("path")]
    if disks:
        lines.append(f"DISKOPTS=\"-m sys {disks[0]}\"")
    else:
        lines.append("DISKOPTS=\"-m sys /dev/sda\"")

    if doc.get("keys"):
        warn("hardware key matrix (keys[]) requires cryptsetup/fido2 post-install setup on Alpine")

    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("file", type=pathlib.Path)
    ap.add_argument("--out", type=pathlib.Path, default=pathlib.Path("."))
    ap.add_argument("--strict", action="store_true", help="exit non-zero if core intent dropped")
    args = ap.parse_args()

    doc = json.loads(args.file.read_text())
    if not str(doc.get("lis", "")).startswith("0.1."):
        sys.exit(f"unsupported LIS version: {doc.get('lis')!r}")

    ans = render_alpine(doc)
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "answers").write_text(ans)
    print(f"wrote {args.out}/answers ({len(WARNINGS)} warning(s))")
    if args.strict and WARNINGS:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
