#!/usr/bin/env python3
"""lis2kickstart — translate a LIS document into Fedora / RHEL Kickstart file (ks.cfg).

Usage: lis2kickstart.py FILE.lis.json [--out DIR] [--strict]

Writes ks.cfg into DIR (default '.'):
  ks.cfg   — Anaconda kickstart file for Fedora, RHEL, Rocky, Alma, CentOS

Best-effort: core intent that Kickstart cannot express is reported as a warning;
with --strict any dropped intent exits non-zero (SPEC §2.3).
"""

import argparse
import json
import pathlib
import sys

WARNINGS: list[str] = []


def warn(msg: str) -> None:
    WARNINGS.append(msg)
    print(f"warning: {msg}", file=sys.stderr)


def render_kickstart(doc: dict) -> str:
    system = doc.get("system", {}) or {}
    boot = doc.get("boot", {}) or {}
    storage = doc.get("storage", {}) or {}
    target = doc.get("target", {}) or {}
    software = doc.get("software", {}) or {}
    desktop = doc.get("desktop", {}) or {}
    scripts = doc.get("scripts", {}) or {}
    users = doc.get("users", []) or []

    lines: list[str] = ["# Generated by lis2kickstart (Linux Installation Specification)", ""]

    # System settings
    lang = system.get("locale", "en_US.UTF-8")
    lines.append(f"lang {lang}")

    keymap = (system.get("keymap", {}) or {}).get("console", "us")
    lines.append(f"keyboard --vckeymap={keymap} --xlayouts={keymap}")

    tz = system.get("timezone", "UTC")
    utc = " --isUtc" if (system.get("hwclock") == "utc" or True) else ""
    lines.append(f"timezone {tz}{utc}")

    if host := system.get("hostname"):
        lines.append(f"network --hostname={host}")

    # Root / User accounts
    has_root = False
    for u in users:
        if u["name"] == "root":
            has_root = True
            if h := (u.get("password") or {}).get("hash"):
                lines.append(f"rootpw --iscrypted {h}")
            break
    if not has_root:
        lines.append("rootpw --lock")

    for u in users:
        if u["name"] == "root":
            continue
        cmd = f"user --name={u['name']}"
        if u.get("admin"):
            cmd += " --groups=wheel"
        elif u.get("groups"):
            cmd += f" --groups={','.join(u['groups'])}"
        if h := (u.get("password") or {}).get("hash"):
            cmd += f" --password={h} --iscrypted"
        lines.append(cmd)

    # Bootloader & Partitioning
    lines.append("bootloader --location=mbr")
    if storage.get("wipe"):
        lines.append("clearpart --all --initlabel")

    disks = {d["id"]: (d.get("match", {}) or {}).get("path") for d in target.get("disks", [])}
    for part in storage.get("partitions", []):
        disk_path = disks.get(part.get("disk"))
        ondisk = f" --ondisk={disk_path.split('/')[-1]}" if disk_path else ""
        role = part.get("role")
        fs = part.get("fs") or "ext4"
        fs_flag = f"--fstype={fs}" if fs != "none" else ""
        size = part.get("size", "rest")

        if size == "rest":
            size_flag = "--size=1 --grow"
        elif size.endswith("GiB"):
            size_flag = f"--size={int(size[:-3]) * 1024}"
        elif size.endswith("MiB"):
            size_flag = f"--size={int(size[:-3])}"
        else:
            size_flag = "--size=4096"

        mnt = part.get("mountpoint") or ("/" if role == "root" else "/boot/efi" if role == "esp" else "")
        if mnt:
            lines.append(f"part {mnt} {fs_flag} {size_flag}{ondisk}")

    # Services
    services = software.get("services", {}) or {}
    en = services.get("enable", [])
    if en:
        lines.append(f"services --enabled={','.join(en)}")

    # Packages Section
    lines.append("")
    lines.append("%packages")
    lines.append("@core")
    
    role = software.get("role", "")
    role_groups = {
        "desktop:gnome": "@gnome-desktop",
        "desktop:kde": "@kde-desktop",
        "desktop:xfce": "@xfce-desktop"
    }
    if role in role_groups:
        lines.append(role_groups[role])
    elif role == "server":
        lines.append("@server-product")

    # software.packages + software.apps
    pkgs = list(software.get("packages", []))
    for app in software.get("apps", []):
        if isinstance(app, str):
            pkgs.append(app)
        elif isinstance(app, dict):
            if name := (app.get("package") or app.get("name")):
                pkgs.append(name)

    for p in pkgs:
        lines.append(p)
    for ex in software.get("exclude", []):
        lines.append(f"-{ex}")
    lines.append("%end")

    # %pre scripts
    early_scripts = []
    for stage in ("pre_install", "pre", "post_storage"):
        for s in scripts.get(stage, []):
            if c := s.get("content"):
                early_scripts.append(c)
    if early_scripts:
        lines.append("")
        lines.append("%pre")
        lines.extend(early_scripts)
        lines.append("%end")

    # %post scripts
    late_scripts = []
    for stage in ("post_install", "post", "pre_reboot", "on_success", "firstboot"):
        for s in scripts.get(stage, []):
            if c := s.get("content"):
                late_scripts.append(c)
    
    for u in users:
        if u_scripts := u.get("scripts", {}):
            for stage in ("post_install", "firstboot"):
                for s in u_scripts.get(stage, []):
                    if c := s.get("content"):
                        late_scripts.append(f"su - {u['name']} -c {json.dumps(c)}")

    if late_scripts:
        lines.append("")
        lines.append("%post")
        lines.extend(late_scripts)
        lines.append("%end")

    if doc.get("keys"):
        warn("hardware key matrix (keys[]) requires manual systemd-cryptenroll in %post")

    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("file", type=pathlib.Path)
    ap.add_argument("--out", type=pathlib.Path, default=pathlib.Path("."))
    ap.add_argument("--strict", action="store_true", help="exit non-zero if core intent dropped")
    args = ap.parse_args()

    doc = json.loads(args.file.read_text())
    if not str(doc.get("lis", "")).startswith("0.1."):
        sys.exit(f"unsupported LIS version: {doc.get('lis')!r}")

    ks = render_kickstart(doc)
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "ks.cfg").write_text(ks)
    print(f"wrote {args.out}/ks.cfg ({len(WARNINGS)} warning(s))")
    if args.strict and WARNINGS:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
