#!/usr/bin/env python3
"""lis2alpine — translate a LIS document into an Alpine `setup-alpine` answerfile.

Usage: lis2alpine.py FILE.lis.{json,yaml} [--out DIR] [--lenient] [--apply]

Writes into DIR (default '.'):
  answers      — setup-alpine answerfile
  lis-post.sh  — post-install hooks setup-alpine has no vocabulary for

`--apply` runs `setup-alpine -f answers` and then the post script against the
installed root; setup-alpine does the partitioning and bootstrap.

setup-alpine's answerfile is a coarse instrument: it takes a whole disk and a
usage mode, not a partition table. Fail-closed by default (SPEC §2.3), so a
document describing a layout Alpine cannot honor is refused rather than
quietly installed as something else.
"""

import argparse
import base64
import json
import pathlib
import sys

from lis_common import (track, check_unread, file_commands, uid_commands, password_field, shell_packages, check_arch, check_script_fields, APPLY_TIME_PATHS,ALL_SECTIONS, add_common_args, check_firmware,
                        check_unhandled, check_section_fields, sudoers_commands, check_kernel_variant, check_mirror, boot_timeout_commands, driver_packages,
                        check_boot_extras, check_keymap, check_version, enforce,
                        load_doc, refuse, report, role_fs, role_mountpoint, warn)


def render_alpine(doc: dict) -> tuple[str, str, str]:
    system = doc.get("system", {}) or {}
    storage = doc.get("storage", {}) or {}
    target = doc.get("target", {}) or {}
    software = doc.get("software", {}) or {}
    network = doc.get("network", {}) or {}
    scripts = doc.get("scripts", {}) or {}
    users = doc.get("users", []) or []

    if not storage.get("wipe", False):
        # lis-prepare.sh runs `parted mklabel` and mkfs with -f/-F: whatever is
        # on the disk is gone. A document that withholds storage.wipe must not
        # have its disk rewritten anyway.
        refuse("storage.wipe: false — this applier lays the disk out from "
               "scratch (parted mklabel + mkfs) and cannot preserve an "
               "existing layout")

    lines: list[str] = ["# Generated by lis2alpine (Linux Installation Specification)", ""]

    km = system.get("keymap", {}) or {}
    # setup-keymap takes a layout and a variant file, e.g. `de de-nodeadkeys`.
    console = km.get("console")
    layout = km.get("layout") or console or "us"
    if console and km.get("layout") and console != km["layout"]:
        warn(f"system.keymap.console {console!r} is not applied — setup-keymap "
             f"takes one layout, and layout {km['layout']!r} was declared")
    variant = f"{layout}-{km['variant']}" if km.get("variant") else layout
    lines.append(f'KEYMAPOPTS="{layout} {variant}"')
    lines.append(f'HOSTNAMEOPTS="{system.get("hostname", "alpine")}"')
    lines.append(f'TIMEZONEOPTS="{system.get("timezone", "UTC")}"')

    if locale := system.get("locale"):
        warn(f"system.locale {locale!r} is not applied — Alpine is musl-based "
             "and setup-alpine has no locale step")
    manager = network.get("manager", "auto")
    if manager not in ("auto", "networkmanager"):
        refuse(f"network.manager {manager!r}: setup-alpine configures /etc/network/interfaces")
    if network.get("wifi"):
        refuse("network.wifi is not expressible in a setup-alpine answerfile")
    if network.get("firewall"):
        refuse("network.firewall is not expressible in a setup-alpine answerfile")
    interfaces = network.get("interfaces", []) or []
    if interfaces:
        refuse("network.interfaces: static addressing is not generated by this applier")
    lines.append('INTERFACESOPTS="auto lo\\niface lo inet loopback\\n\\n'
                 'auto eth0\\niface eth0 inet dhcp\\n"')
    lines.append('DNSOPTS="-n 1.1.1.1"')

    proxy = (doc.get("proxy", {}) or {}).get("http")
    lines.append(f'PROXYOPTS="{proxy or "none"}"')
    mirror = (doc.get("mirror", {}) or {}).get("url")
    lines.append(f'APKREPOSOPTS="{mirror or "-1"}"')

    ssh = network.get("ssh", {}) or {}
    lines.append(f'SSHDOPTS="{"openssh" if ssh.get("enabled") else "none"}"')
    time_cfg = system.get("time", {}) or {}
    provider = time_cfg.get("provider", "auto")
    ntp = {"auto": "chrony", "chrony": "chrony", "openntpd": "openntpd",
           "systemd-timesyncd": None}.get(provider, None)
    if time_cfg.get("ntp") is False:
        ntp = "none"
    elif ntp is None:
        refuse(f"system.time.provider {provider!r} is not available on Alpine")
        ntp = "chrony"
    lines.append(f'NTPOPTS="{ntp}"')

    # Storage. setup-disk has two modes and the document decides which fits:
    # given a disk it partitions and formats one itself (steered by the
    # BOOTLOADER/ROOTFS/BOOTFS/DISKLABEL environment), and given a mountpoint it
    # installs into filesystems that are already prepared. Anything setup-disk
    # cannot lay out itself — subvolumes above all — takes the second path,
    # which is Alpine's own documented flow for custom layouts.
    disks = [(d.get("match", {}) or {}).get("path") for d in target.get("disks", [])]
    disks = [d for d in disks if d]
    if len(disks) != len(target.get("disks", [])):
        refuse("some target.disks have no match.path — setup-disk needs a device path")
    # This applier installs to a single device, so the disk and partition
    # handles are structural rather than actionable — but they are consulted
    # here so the document is not left with fields nothing ever looked at.
    for entry in target.get("disks", []) or []:
        _ = entry.get("id")
    for part in storage.get("partitions", []) or []:
        _ = part.get("disk"), part.get("id")
    if len(disks) > 1:
        refuse(f"{len(disks)} disks declared: setup-disk installs to a single device")
    disk = disks[0] if disks else "/dev/vda"

    for what, present in (("storage.encryption", storage.get("encryption")),
                          ("storage.lvm", storage.get("lvm")),
                          ("storage.raid", storage.get("raid"))):
        if present:
            refuse(f"{what} is not generated by this applier for Alpine")
    if (storage.get("snapshots", {}) or {}).get("enabled"):
        refuse("storage.snapshots is not expressible for Alpine")

    partitions = [p for p in storage.get("partitions", []) or [] if not p.get("existing")]
    for i, part in enumerate(storage.get("partitions", []) or []):
        if part.get("existing"):
            refuse(f"partition {i}: adopting an existing partition is not expressible")
        fs = role_fs(part)
        if fs not in (None, "none", "ext2", "ext3", "ext4", "btrfs", "xfs", "vfat", "swap"):
            refuse(f"partition {i}: setup-disk cannot format {fs!r}")

    root = next((p for p in partitions if role_mountpoint(p) == "/"), None)
    boot_part = next((p for p in partitions
                      if role_mountpoint(p) in ("/boot", "/boot/efi")), None)
    manual = bool(root and root.get("subvolumes"))

    env: list[str] = []
    loader = (doc.get("boot", {}) or {}).get("loader", "auto")
    bootloader = {"auto": None, "grub": "grub", "syslinux": "syslinux",
                  "limine": "limine", "none": "none"}.get(loader, "")
    if bootloader == "":
        refuse(f"boot.loader {loader!r} is not one of setup-disk's bootloaders")
        bootloader = None
    if bootloader:
        env.append(f"BOOTLOADER={bootloader}")
    if target.get("firmware") == "uefi":
        env.append("USE_EFI=1")
    env.append("DISKLABEL=" + ("gpt" if target.get("firmware") == "uefi" else "dos"))
    # Alpine's initramfs only loads the modules named on the kernel command
    # line. Shipping the root filesystem's module in the image is not enough:
    # without `modules=`, mount fails before the filesystem type is registered.
    kernel_opts = list(((doc.get("boot", {}) or {}).get("kernel", {}) or {})
                       .get("params", []))
    if root and (fs := role_fs(root)) and fs not in (None, "none"):
        modules = ["sd-mod", "usb-storage", "virtio-blk", "virtio-pci", fs]
        kernel_opts.append("modules=" + ",".join(dict.fromkeys(modules)))
        kernel_opts.append(f"rootfstype={fs}")
    if kernel_opts:
        env.append("KERNELOPTS=" + shquote(" ".join(kernel_opts)))
    if root and (fs := role_fs(root)) and fs != "none":
        env.append(f"ROOTFS={fs if not manual else 'btrfs'}")
    if boot_part and (fs := role_fs(boot_part)) and fs != "none":
        env.append(f"BOOTFS={fs}")

    if manual:
        # setup-alpine must not touch the disk: the prepare script below lays it
        # out, and setup-disk is handed the resulting mountpoint.
        lines.append('DISKOPTS="none"')
        warn("btrfs subvolumes: the disk is prepared by lis-prepare.sh and handed to "
             "`setup-disk <mountpoint>`, Alpine's documented flow for custom layouts")
    else:
        lines.append(f'DISKOPTS="-m sys {disk}"')
    lines.append('LBUOPTS="none"')
    lines.append('APKCACHEOPTS="none"')

    normal = [u for u in users if u["name"] != "root"]
    if normal:
        primary = normal[0]
        admin = "-a " if primary.get("admin") else ""
        lines.append(f'USEROPTS="{admin}-g wheel {primary["name"]}"')
        password = primary.get("password") or {}
        if not password.get("hash") and not password.get("locked"):
            refuse(f"user '{primary['name']}': no password hash and not marked locked")
        if keys := primary.get("ssh_authorized_keys"):
            lines.append(f'USERSSHKEY="{keys[0]}"')

    # Everything setup-alpine has no answer key for goes into a post script that
    # --apply runs against the installed root. Nothing is silently dropped.
    post: list[str] = ["#!/bin/sh", "# Generated by lis2alpine — run against the installed root.",
                       "set -e", 'target="${1:-/mnt}"']

    packages = list(software.get("packages", []))
    packages += driver_packages(doc, "alpine")
    # setup-alpine installs these before the post script runs, so a declared
    # login shell exists by the time anything tries to use it.
    packages += shell_packages(doc)
    if kernel_pkg := check_kernel_variant(doc, {"lts": "linux-lts"}, "Alpine"):
        packages.append(kernel_pkg)
    for app in software.get("apps", []):
        if isinstance(app, str):
            packages.append(app)
        elif isinstance(app, dict):
            if name := (app.get("package") or app.get("name")):
                packages.append(name)
    role = software.get("role", "")
    if role in ("desktop:gnome", "desktop:kde", "desktop:xfce"):
        packages.append({"desktop:gnome": "gnome", "desktop:kde": "plasma",
                         "desktop:xfce": "xfce4"}[role])
    elif role not in ("", "minimal", "server"):
        refuse(f"software.role {role!r} has no Alpine package set")
    if packages:
        post.append(f'apk --root "$target" add {" ".join(packages)}')
    if software.get("exclude"):
        refuse("software.exclude has no Alpine equivalent")
    if software.get("snap") or software.get("flatpak"):
        refuse("software.snap/flatpak are not available on Alpine")

    root_user = next((u for u in users if u["name"] == "root"), None)
    root_password = (root_user or {}).get("password") or {}
    if root_field := password_field(root_user or {}):
        post.append(f'chroot "$target" usermod -p {shquote(root_field)} root')
    else:
        # setup-alpine -e leaves root open; a document that does not grant root
        # a password must not end up with a passwordless one.
        post.append('chroot "$target" passwd -l root')
        if root_user and not root_password.get("locked"):
            warn("users['root'] has no password hash; the account is locked")

    if normal:
        # setup-alpine's USEROPTS only understands the admin group, so anything
        # else the document declares for the primary user has to be added here
        # or it would be dropped without a word.
        primary_user = normal[0]
        for group in primary_user.get("groups", []) or []:
            post.append(f'chroot "$target" addgroup -S {group} 2>/dev/null || true')
            post.append(f'chroot "$target" addgroup {primary_user["name"]} {group}')
        if field := password_field(primary_user):
            # busybox has no usermod; chpasswd -e takes the crypt(3) hash
            # directly. Single-quoted, or the shell would eat the $-delimited
            # fields of the hash itself.
            post.append(f'echo {shquote(primary_user["name"] + ":" + field)} '
                        f'| chroot "$target" chpasswd -e')
        # USEROPTS carries neither of these either.
        if shell := primary_user.get("shell"):
            post.append(f'chroot "$target" sed -i '
                        + shquote(f"s|^\\({primary_user['name']}:[^:]*:[^:]*:[^:]*:[^:]*:[^:]*\\):.*|\\1:{shell}|")
                        + ' /etc/passwd')
        if comment := primary_user.get("comment"):
            post.append(f'chroot "$target" chfn -f {json.dumps(comment)} '
                        f'{primary_user["name"]} 2>/dev/null || true')

    for user in normal[1:]:
        password = user.get("password") or {}
        if not password.get("hash") and not password.get("locked"):
            refuse(f"user '{user['name']}': no password hash and not marked locked")
        groups = ",".join(user.get("groups", []))
        add = 'adduser -D'
        if shell := user.get("shell"):
            add += f" -s {shell}"
        if comment := user.get("comment"):
            add += f" -g {json.dumps(comment)}"
        post.append(f'chroot "$target" {add} {user["name"]}')
        if field := password_field(user):
            post.append(f'chroot "$target" usermod -p {json.dumps(field)} {user["name"]}')
        for group in groups.split(",") if groups else []:
            post.append(f'chroot "$target" addgroup {user["name"]} {group} || true')

    for unit in (software.get("services", {}) or {}).get("enable", []) or []:
        post.append(f'chroot "$target" rc-update add {unit} default')
    for unit in (software.get("services", {}) or {}).get("disable", []) or []:
        post.append(f'chroot "$target" rc-update del {unit} default || true')

    for entry in doc.get("files", []) or []:
        for cmd in file_commands(entry, prefix='"$target"'):
            post.append(cmd)

    for cmd in sudoers_commands(doc):
        post.append(f'chroot "$target" sh -c {json.dumps(cmd)}')
    for cmd in uid_commands(doc):
        post.append(f'chroot "$target" sh -c {json.dumps(cmd)}')

    for stage in ("post_storage", "post_install", "post", "pre_reboot", "on_success"):
        for s in scripts.get(stage, []):
            if c := s.get("content"):
                post.append(f'chroot "$target" sh -c {json.dumps(c)}')
    for user in users:
        for s in (user.get("scripts", {}) or {}).get("post_install", []):
            if c := s.get("content"):
                post.append(f'chroot "$target" su - {user["name"]} -c {json.dumps(c)}')

    firstboot = [s["content"] for s in scripts.get("firstboot", []) if s.get("content")]
    for user in users:
        for s in (user.get("scripts", {}) or {}).get("firstboot", []):
            if c := s.get("content"):
                firstboot.append(f'su - {user["name"]} -c {json.dumps(c)}')
    if firstboot:
        script = ("#!/sbin/openrc-run\ncommand=/usr/local/bin/lis-firstboot\n"
                  "depend() { after net; }\n")
        body = ("#!/bin/sh\n" + "\n".join(firstboot)
                + "\nrc-update del lis-firstboot default\n")
        post.append(f'echo {base64.b64encode(body.encode()).decode()} | base64 -d '
                    '> "$target/usr/local/bin/lis-firstboot"')
        post.append('chmod 755 "$target/usr/local/bin/lis-firstboot"')
        post.append(f'echo {base64.b64encode(script.encode()).decode()} | base64 -d '
                    '> "$target/etc/init.d/lis-firstboot"')
        post.append('chmod 755 "$target/etc/init.d/lis-firstboot"')
        post.append('chroot "$target" rc-update add lis-firstboot default')

    if scripts.get("pre_install") or scripts.get("pre"):
        warn("scripts.pre_install runs before setup-alpine from --apply, "
             "not from the answerfile (setup-alpine has no pre hook)")
    if scripts.get("on_error"):
        refuse("scripts.on_error has no setup-alpine equivalent")
    if doc.get("desktop", {}).get("autologin"):
        refuse("desktop.autologin is not expressible for Alpine by this applier")
    if doc.get("keys"):
        refuse("keys[] hardware-token enrollment is not expressible for Alpine")
    if doc.get("registration"):
        refuse("registration does not apply to Alpine")
    if (boot := doc.get("boot", {}) or {}).get("loader") not in (None, "auto", "grub", "syslinux"):
        refuse(f"boot.loader {boot['loader']!r}: setup-disk installs syslinux or grub")
    if (boot.get("kernel", {}) or {}).get("variant") not in (None, "default", "lts"):
        refuse(f"boot.kernel.variant {boot['kernel']['variant']!r} has no Alpine package")

    # Birth certificate (delivery.md §8).
    birth = base64.b64encode(json.dumps(doc, separators=(",", ":")).encode()).decode()
    post.append('install -d -m755 "$target/var/lib/lis"')
    post.append(f'echo {birth} | base64 -d > "$target/var/lib/lis/system.lis.json"')
    post.append('chmod 600 "$target/var/lib/lis/system.lis.json"')

    prepare = (prepare_script(disk, partitions, root, boot_part, env,
                              (doc.get("boot") or {}).get("timeout"))
               if manual else "")
    return "\n".join(lines) + "\n", "\n".join(post) + "\n", prepare


MOUNT = "/mnt/lis"


def prepare_script(disk, partitions, root, boot_part, env, timeout=None) -> str:
    """Lay out the disk, then hand the mounted root to setup-disk.

    Alpine's answerfile has no vocabulary for a partition table — `DISKOPTS`
    takes a whole disk and a mode. Its documented route for anything finer is to
    prepare the filesystems and run `setup-disk <mountpoint>`, which is what
    this does: setup-disk still installs the system, writes fstab and lays down
    the bootloader.
    """
    steps = ["#!/bin/sh",
             "# Generated by lis2alpine — prepares the layout for `setup-disk`.",
             "set -eux", f"disk={shquote(disk)}", f"mnt={shquote(MOUNT)}",
             "apk add --no-progress btrfs-progs e2fsprogs xfsprogs dosfstools parted",
             # apk brings the userspace tools; the kernel modules for the
             # filesystems the document asks for still have to be loaded, or
             # mount fails with EINVAL on a filesystem it cannot recognise.
             "for m in " + " ".join(sorted({role_fs(p) for p in partitions
                                            if role_fs(p) not in (None, "none", "swap")}))
             + "; do modprobe \"$m\" 2>/dev/null || true; done",
             "parted -s \"$disk\" mklabel " + ("gpt" if "USE_EFI=1" in env else "msdos")]

    start = "1MiB"
    numbered = []
    for index, part in enumerate(partitions, start=1):
        size = part.get("size", "rest")
        end = "100%" if size == "rest" else f"{cumulative(partitions[:index])}"
        steps.append(f'parted -s "$disk" -- mkpart primary {start} {end}')
        if part.get("role") in ("esp", "boot"):
            steps.append(f'parted -s "$disk" set {index} boot on')
        start = end
        numbered.append((index, part))
    steps.append('partprobe "$disk" || true')
    steps.append("sleep 2")

    for index, part in numbered:
        dev = f'"${{disk}}{index}"'
        fs = role_fs(part)
        if fs == "swap":
            steps.append(f"mkswap {dev}")
        elif fs == "vfat":
            steps.append(f"mkfs.vfat -F32 {dev}")
        elif fs and fs != "none":
            steps.append(f"mkfs.{fs} -f {dev}" if fs in ("btrfs", "xfs")
                         else f"mkfs.{fs} -F {dev}")
        if part is root:
            steps.append(f'rootdev={dev}')
        if part is boot_part:
            steps.append(f'bootdev={dev}')

    subvols = root.get("subvolumes", []) or []
    root_sub = next((s for s in subvols if s["mountpoint"] == "/"), None)
    steps += [f'mkdir -p "$mnt"', 'mount "$rootdev" "$mnt"']
    for sub in subvols:
        steps.append(f'btrfs subvolume create "$mnt/{sub["name"]}"')
    if root_sub:
        # Alpine's initramfs mounts the root device with no subvol= of its own,
        # so it would land on the top level — which holds only the subvolumes
        # and no init. Making the root subvolume the filesystem default is what
        # a plain mount then resolves to.
        steps.append(f'btrfs subvolume set-default "$mnt/{root_sub["name"]}" '
                     f'|| btrfs subvolume set-default '
                     f'"$(btrfs subvolume list "$mnt" | '
                     f'awk \'$NF=="{root_sub["name"]}" {{print $2}}\' | head -n1)" "$mnt"')
    steps.append('umount "$mnt"')
    if root_sub:
        steps.append(f'mount -o subvol={root_sub["name"]} "$rootdev" "$mnt"')
    else:
        steps.append('mount "$rootdev" "$mnt"')
    for sub in subvols:
        if sub is root_sub:
            continue
        steps += [f'mkdir -p "$mnt{sub["mountpoint"]}"',
                  f'mount -o subvol={sub["name"]} "$rootdev" "$mnt{sub["mountpoint"]}"']
    if boot_part:
        steps += ['mkdir -p "$mnt/boot"', 'mount "$bootdev" "$mnt/boot"']

    exports = " ".join(env)
    install = 'setup-disk -m sys "$mnt"'
    steps.append(f"{exports} {install}" if exports else install)

    # A btrfs root needs the module in the initramfs; Alpine's default feature
    # set does not include it and the kernel then cannot mount its own root.
    root_fs = role_fs(root)
    if root_fs and root_fs not in ("ext4", "none"):
        steps.append(
            'chroot "$mnt" sh -c ' + shquote(
                f'sed -i \'s/^features="\\(.*\\)"/features="\\1 {root_fs}"/\' '
                "/etc/mkinitfs/mkinitfs.conf; "
                "for k in /lib/modules/*; do mkinitfs -b / $(basename $k); done"))

    # setup-disk's mountpoint mode populates the root and writes fstab, but the
    # alpine-conf on the current ISO (3.21) has no bootloader option for that
    # mode at all and leaves the disk unbootable — a clean exit status and
    # nothing that boots. Lay the bootloader down with the target's own grub.
    loader = next((e.split("=", 1)[1] for e in env if e.startswith("BOOTLOADER=")), "grub")
    if loader == "grub":
        efi = "USE_EFI=1" in env
        params = next((e.split("=", 1)[1] for e in env
                       if e.startswith("KERNELOPTS=")), "''")
        steps += [
            'for d in dev proc sys; do mount --bind "/$d" "$mnt/$d"; done',
            'chroot "$mnt" apk add --no-progress grub '
            + ("grub-efi efibootmgr" if efi else "grub-bios"),
            # The value must be quoted in the file: /etc/default/grub is sourced
            # by a shell, so an unquoted multi-word cmdline would be truncated
            # at the first space and the rest run as a command.
            'printf \'GRUB_CMDLINE_LINUX_DEFAULT="%s"\\n'
            'GRUB_TERMINAL="serial console"\\n'
            "GRUB_SERIAL_COMMAND=\"serial --unit=0 --speed=115200\"\\n' "
            + params + ' > "$mnt/etc/default/grub"',
            *([f'echo GRUB_TIMEOUT={int(timeout)} >> "$mnt/etc/default/grub"']
              if timeout is not None else []),
            'chroot "$mnt" grub-install '
            + ("--target=x86_64-efi --efi-directory=/boot --removable"
               if efi else '--target=i386-pc "$disk"'),
            'chroot "$mnt" grub-mkconfig -o /boot/grub/grub.cfg',
            'for d in sys proc dev; do umount "$mnt/$d" || true; done',
        ]
    elif loader != "none":
        warn(f"boot.loader {loader!r}: setup-disk installs it, but this applier "
             "does not verify the result for anything but grub")
    return "\n".join(steps) + "\n"


def cumulative(parts) -> str:
    """Absolute end offset of the last partition in the list, as a parted size."""
    total = 0
    for part in parts:
        size = part.get("size", "rest")
        for unit, mib in (("TiB", 1024 * 1024), ("GiB", 1024), ("MiB", 1)):
            if size.endswith(unit):
                total += int(size[: -len(unit)]) * mib
                break
    return f"{total + 1}MiB"


def shquote(value: str) -> str:
    """Single-quote a value for the generated shell scripts."""
    return "'" + value.replace("'", "'\\''") + "'"


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Translate a LIS document into an Alpine setup-alpine answerfile.")
    add_common_args(ap)
    ap.add_argument("--apply", "-a", action="store_true",
                    help="run setup-alpine with the answerfile, then the post script")
    args = ap.parse_args()

    doc = track(load_doc(args.file))
    check_version(doc, args.file)
    check_firmware(doc)
    check_unhandled(doc, ALL_SECTIONS)
    check_boot_extras(doc, {"loader", "timeout", "kernel", "variant"})
    check_mirror(doc, {"url"})
    check_section_fields(doc, "desktop", {"autologin"})
    check_section_fields(doc, "installer", set())
    check_keymap(doc, {"console", "layout", "variant"})

    answers, post, prepare = render_alpine(doc)
    # Resolve now: --out defaults to '.', and a bare relative name is not
    # executable by path when these scripts are handed to subprocess.
    args.out = args.out.resolve()
    args.out.mkdir(parents=True, exist_ok=True)
    ans_file = args.out / "answers"
    post_file = args.out / "lis-post.sh"
    ans_file.write_text(answers)
    post_file.write_text(post)
    post_file.chmod(0o755)
    written = [ans_file, post_file]
    prepare_file = args.out / "lis-prepare.sh"
    if prepare:
        prepare_file.write_text(prepare)
        prepare_file.chmod(0o755)
        written.append(prepare_file)
    report(*written)

    # Fail closed *before* touching the machine, not after.
    check_arch(doc, {"x86_64"})
    check_script_fields(doc)
    check_unread(doc, ignore=APPLY_TIME_PATHS)

    if status := enforce(args.strict):
        return status

    if args.apply:
        import shutil
        import subprocess
        if not shutil.which("setup-alpine"):
            sys.exit("error: --apply requested, but 'setup-alpine' is not on PATH "
                     "(are you running on the Alpine live image?)")
        for stage in ("pre_install", "pre"):
            for item in (doc.get("scripts", {}) or {}).get(stage, []):
                if content := item.get("content"):
                    subprocess.run(content, shell=True, check=False)
        # -e skips the interactive root password prompt; the answerfile has no
        # vocabulary for it, and what root's password should be is the
        # document's business, applied by the post script below.
        res = subprocess.run(["setup-alpine", "-e", "-f", str(ans_file)])
        if res.returncode != 0:
            return res.returncode
        target = "/mnt"
        if prepare:
            res = subprocess.run(["sh", str(prepare_file)])
            if res.returncode != 0:
                return res.returncode
            target = MOUNT
        return subprocess.run(["sh", str(post_file), target]).returncode
    return 0


if __name__ == "__main__":
    sys.exit(main())
